version: "3.8"

services:
  postgres:
    image: postgres:14.5
    shm_size: 128mb
    volumes:
      - ./database/data/postgresql:/var/lib/postgresql/data
      - ./database/scripts/1_schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=rozliv_bazi