version: "3.8"

services:
  database:
    image: postgres:14.5
    shm_size: 128mb
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - ./.env
  cms:
    image: node:16-alpine3.16
    ports:
      - "1337:1337"
    env_file:
      - ./.env
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 1337
      APP_KEYS: "toBeModified1,toBeModified2"
    volumes:
      - "./cms:/app"
    working_dir: /app
    command: sh -c "cd /app; npm install --platform=linuxmusl; npm run develop"

  telegram:
    image: node:16-alpine3.16
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
    volumes:
      - "./telegram:/app"
    working_dir: /app
    command: sh -c "cd /app; npm install --platform=linuxmusl; npm run develop"